language: c

os: linux
dist: trusty
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libhidapi-dev libusb-1.0-0-dev

before_script:
    - ./autogen.sh

script:
    - make
